version: '3.5'

services:

  mongo:
    image: mongo:3.4.18
    container_name: indyscan-mongo
    networks:
    - indynet
    volumes:
    -  indyscandb:/data/db
    ports:
    - 27017:27017

  indyscan:
    image: indyscan:latest-local
    container_name: indyscan-webapp
    networks:
    - indynet
    depends_on:
    - mongo
    environment:
    - URL_MONGO=mongodb://mongo.indynet:27017
    - INDY_NETWORKS=${INDY_NETWORKS}
    ports:
    - '3000:3000'

  indyscan-daemon:
    image: indyscan-daemon:latest-local
    container_name: indyscan-daemon
    volumes:
      - ${HOME}/.indy_client/pool:/home/indyscan/.indy_client/pool
    networks:
    - indynet
    depends_on:
    - mongo
    environment:
    - URL_MONGO=mongodb://mongo.indynet:27017
    - INDY_NETWORKS=${INDY_NETWORKS}

volumes:
  indyscandb:
    external: false
  indypools:
    external: false

networks:
  indynet:
    name: indynet
    driver: bridge
